let din = [
    {
        name:'din1',
        price:'50,000frs',
        location:'Bamenda',
        image:'./Defence/Images/din1.jpg'
    },
    {
        name:'din2',
        price:'450,000frs',
        location:'Douala',
        image:'./Defence/Images/din2.jpg'
    },
    {
        name:'din3',
        price:'200,000frs',
        location:'Bamenda',
        image:'./Defence/Images/din3.jpg'
    },
    {
        name:'din4',
        price:'50,000frs',
        location:'Bamenda',
        image:'./Defence/Images/din4.jpg'
    },
    {
        name:'din5',
        price:'80,000frs',
        location:'Yaounde',
        image:'./Defence/Images/din5.jpg'
    },
    {
        name:'din6',
        price:'90,000frs',
        location:'Bamenda',
        image:'./Defence/Images/din6.jpg'
    },
    {
        name:'din7',
        price:'120,000frs',
        location:'Bamenda',
        image:'./Defence/Images/din7.jpg'
    },
    {
        name:'din8',
        price:'70,000frs',
        location:'Bamenda',
        image:'./Defence/Images/din8.jpg'
    },
    {
        name:'din9',
        price:'90,000frs',
        location:'Bamenda',
        image:'./Defence/Images/din9.jpg'
    },
]
